### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by PraveenOjha** [notAperson535/OneClick-macOS-Simple-KVM#92] opened 2023-08-13 20:24 UTC
**Which operating system are you trying to install?**
 macOS Monterey 

**Describe the bug**
When the kernal of linux get updated from ver 6.4.8 zen to above 
the vm crashes with 
matching deferred by IOUSBHostHIDDevice error 

**To Reproduce**
 
 

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - working fine on kernal version 6.4.8 
 - problem when updating the kernal to newer version 6.4.9 or above

**Comment by Dravelz-21** [comment] 2023-08-13 21:17
can confirm downgrading to 6.4.8 kernel fixes the issue for me aswell.

**Comment by notAperson535** [comment] 2023-08-13 21:43
Duplicate of #93

**Closed** 2023-08-13 21:44 UTC
Labels: bug
