### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by secdoc** [notAperson535/OneClick-macOS-Simple-KVM#43] opened 2022-10-20 19:24 UTC
**Which operating system are you trying to install?**
Transfer from macOS-Simple-KVM to upgrade to Monterey

**Describe the bug**
After following the instruction getting the following error:

```
root@maul:/mnt/kvm/OneClick-macOS-Simple-KVM# ./make.sh --add
template.xml has been generated in /mnt/kvm/OneClick-macOS-Simple-KVM
error: Failed to define domain from template.xml
error: Cannot check QEMU binary /run/current-system/sw/bin/qemu-system-x86_64: No such file or directory
```

**To Reproduce**
All you have to do is place the BaseSystem file and the file that has macOS installed into the OneClick-macOS-Simple-KVM folder. Then rename the file that has macOS installed (usually MyDisk.qcow2) to macOS.qcow2. Then run ./basic.sh a

**Expected behavior**
Adding VM to KVM

**Screenshots**
Attached

**Desktop (please complete the following information):**

This is the following information about my system:

```
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 5.19.0-76051900-generic 
Uptime: 10 hours, 16 mins 
Packages: 2493 (dpkg), 58 (flatpak) 
Shell: bash 5.1.16 
Resolution: 1920x1080, 1920x1080, 3440x1440, 3840x2160 
Terminal: gnome-terminal 
CPU: AMD Ryzen 9 5950X (32) @ 3.4GHz [60.6°C] 
GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT 
Memory: 11231MiB / 128730MiB (8%) 
```

**Additional context**
![OneClick_macOS_Simple_KVM](https://user-images.githubusercontent.com/55542561/197039191-57ff32fb-fc80-464f-b0e0-88e81fce5fac.png)

**Comment by notAperson535** [comment] 2022-10-20 19:40
@secdoc  This is a duplicate of #14 and #41. Answer can be found here: https://github.com/notAperson535/OneClick-macOS-Simple-KVM/issues/14#issuecomment-1119259802

(Make sure to use the qemu directory for your Linux repo, they have arch)

**Closed by notAperson535** 2022-10-20 19:40 UTC
Labels: bug

**Comment by secdoc** [comment] 2022-10-20 20:00
Thank you for the support...
